stages:
  - build
  - test
  - deploy

terraform_apply:
  stage: deploy
  image: hashicorp/terraform:latest
  script:
    - terraform init
    - terraform validate
    - terraform plan
    - terraform apply -auto-approve